server:
  port: 3344

spring:
  application:
    name: cloud-config-cenrer
  cloud:
    config:
      server:
        git:
          uri: http://10.102.100.101:8080/r/springcloud-config.git
          search-paths: springcloud-config
      label: master
  rabbitmq:
    host: 10.102.100.101
    port: 5672
    username: guest
    password: guest


# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"

eureka:
  client:
    # 表示是否将自己注册进Eureka默认true
    register-with-eureka: true
    # 是否从EurekaServer抓取已有的注册信息，默认true 单节点无所谓，集群必须为true。才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
            defaultZone: http://localhost:7001/eureka
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka

