server:
  port: 9003

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 10.102.100.101:8847

management:
  endpoints:
    web:
      exposure:
        include: "*"