server:
  port: 80

spring:
  application:
    name: cloud-consumer-order

  cloud:
    consul:
      host: 10.102.100.101
      port: 8510
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true