server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 10.102.100.101:8847
    sentinel:
      transport:
        dashboard: 10.102.100.101:8088
        port: 8719
service-url:
  nacos-user-service: http://naocs-payment-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true