server:
  port: 8401
spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        # Nacos服务注册中心地址
        server-addr: 10.102.100.101:8847
    sentinel:
      transport:
        # sentinel dashboard 地址
        dashboard: 10.102.100.101:8088
        # 默认为8719，如果被占用会自动+1，直到找到为止
        port: 8719
      # 流控规则持久化到nacos
      datasource:
        dsl:
          nacos:
            server-addr: 10.102.100.101:8847
            data-id: ${spring.application.name}
            group-id: DEFAULT_GROUP
            data-type: json
            rule-type: flow
management:
  endpoints:
    web:
      exposure:
        include: "*"


#  [
#  {
#    "resource":"/rateLimit/byUrl",
#    "limitApp":"default",
#    "grade":1,
#    "count":1,
#    "strategy":0,
#    "controlBehavior":0,
#    "clusterMode":false
#  }
#  ]